{{- range $name, $cfg := .Values.services }}
{{- if $cfg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
{{- end }}
{{- end }}
